services:
  php:
    build:
      context: ./.docker/php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
    depends_on:
      - mysql

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-tasklinker}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: app
      PMA_PASSWORD: app
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
